using System;
using System.Collections.Generic;


namespace tusur_informatika_kursovaya
{
    class Animals : Words
    {
        public Animals()
        {
            words.Add("Аардоникс");
            words.Add("Абажуровые пауки");
            words.Add("Абботины");
            words.Add("Абелизавр");
            words.Add("Абелизавриды");
            words.Add("Абидозавр");
            words.Add("Бабакотии");
            words.Add("Бабаксы");
            words.Add("Бабблер - капуцин");
            words.Add("Бабирусса");
            words.Add("Бабка альпийская");
            words.Add("Бабка арктическая");
            words.Add("Вавеликсия");
            words.Add("Валаамка");
            words.Add("Валлаби(род)");
            words.Add("Валлаби Парри");
            words.Add("Валлонииды");
            words.Add("Вальватиды");
            words.Add("Вальдшнеп");
            words.Add("Вальдшнепы");
            words.Add("Вальки");
            words.Add("Вальковатые змеи");
            words.Add("Габонская гадюка");
            words.Add("Габонская крошечная мартышка");
            words.Add("Габонский галаго");
            words.Add("Габонский когтеносец");
            words.Add("Габонский саванный дятел");
            words.Add("Дабб");
            words.Add("Дагестанская ящерица");
            words.Add("Дагестанский тур");
            words.Add("Дазиподы");
            words.Add("Дакнисы");
            words.Add("Евгенеодонтообразные");
            words.Add("Евразийские ежи");
            words.Add("Евразийские летяги");
            words.Add("Евразийский волк");
            words.Add("Европазавр");
            words.Add("Жаба Бломберга");
            words.Add("Жаба Латаста");
            words.Add("Жаба - ага");
            words.Add("Жаба - повитуха");
            words.Add("Жабки");
            words.Add("Забайкальский солонгой");
            words.Add("Заболонник дубовый");
            words.Add("Заболонник ильмовый");
            words.Add("Заболонник ильмовый большой");
            words.Add("Заболонник морщинистый");
            words.Add("Иберийская жаба-повитуха");
            words.Add("Иберийская ящерица");
            words.Add("Иберийский волк");
            words.Add("Иберийский заяц");
            words.Add("Иберомезорнис");
            words.Add("Йеменская синичья славка");
            words.Add("Йодотрофеусы");
            words.Add("Йоровые");
            words.Add("Каама");
            words.Add("Кабан");
            words.Add("Кабарга");
            words.Add("Кабарга Березовского");
            words.Add("Ла - платский дельфин");
            words.Add("Лабеотрофеусы");
            words.Add("Лабидозавр");
            words.Add("Лабидохром Чисумула");
            words.Add("Лабидохромис Фрайберга");
            words.Add("Маврикийская пустельга");
            words.Add("Маврикийская утка");
            words.Add("Маврикийский дронт");
            words.Add("Маврикийский кольчатый попугай");
            words.Add("Маврикийский синий голубь");
            words.Add("Нектокарис");
            words.Add("Нельма");
            words.Add("Нематоды");
            words.Add("Немегтозавр");
            words.Add("Немейский тонкотел");
            words.Add("Немертины");
            words.Add("Обдуродоны");
            words.Add("Обезьянообразные");
            words.Add("Обезьяны");
            words.Add("Обезьяньи мыши");
            words.Add("Обелия");
            words.Add("Павиан анубис");
            words.Add("Павианы");
            words.Add("Павлиний глаз");
            words.Add("Павлиний фазан");
            words.Add("Павлиноглазка Артемида");
            words.Add("Рабдитиды");
            words.Add("Рабдитис");
            words.Add("Рабдодон");
            words.Add("Рабирубия");
            words.Add("Равара");
            words.Add("Табачная белокрылка");
            words.Add("Табачногрудый древолаз");
            words.Add("Табачный жук");
            words.Add("Тава");
            words.Add("Таджикская ящурка");
            words.Add("Уберабатитан");
            words.Add("Увенчанный сифака");
            words.Add("Угандская белозубка-броненоска");
            words.Add("Угловатая лягушка");
            words.Add("Угловатый крестовик");
            words.Add("Фазан аргус");
            words.Add("Фазанка");
            words.Add("Фазановые");
            words.Add("Фазановые(подсемейство)");
            words.Add("Фазановый голубь");
            words.Add("Хабии");
            words.Add("Хагедаш");
            words.Add("Хагерманская лошадь");
            words.Add("Хагрифус");
            words.Add("Хадениновые");
            words.Add("Цаплевые");
            words.Add("Цапли");
            words.Add("Цапля - голиаф");
            words.Add("Цветные бекасы");
            words.Add("Цветные тимелии");
            words.Add("Чавыча");
            words.Add("Чагры");
            words.Add("Чайка Одуэна");
            words.Add("Чайка Тэйера");
            words.Add("Чайка Хартлауба");
            words.Add("Шагреневый скат");
            words.Add("Шагреневый хвостокол");
            words.Add("Шакалы");
            words.Add("Шалфейный тетерев");
            words.Add("Шама - дрозды");
            words.Add("Щавелевая совка");
            words.Add("Щавелевый листоед");
            words.Add("Щеглы");
            words.Add("Щёголь(птица)");
            words.Add("Щелеглазая серая акула");
            words.Add("Эбосии");
            words.Add("Эванииды");
            words.Add("Эварха серповидная");
            words.Add("Эверманнелловые");
            words.Add("Эверсманния украшенная");
            words.Add("Южная короткохвостая бурозубка");
            words.Add("Южная летяга");
            words.Add("Южная путассу");
            words.Add("Южная рексия");
            words.Add("Южная силикуария");
            words.Add("Ящерица");
            words.Add("Ястреб");
            words.Add("Як");

        }
    }
}
